version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - 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=your-openai-api-key-here
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lg99487330
    ports:
      - "5432:5432"
